spring:
  application:
    name: consul-client
#  cloud:
#    consul:
#      host: 122.51.87.142
#      port: 8500
  servlet:
    multipart:
      enabled: true
      max-file-size: 40000MB
      max-request-size: 40000MB